title:              Shentanli's Blog
email:              shentanli@foxmail.com
description:        WAIT AND HOPE!
author:             shentanli
#baseurl:            "/startbootstrap-clean-blog-jekyll"
#url:                "https://blackrockdigital.github.io"
theme: jekyll-theme-clean-blog

# Social Profiles
twitter_username:   shentanli
github_username:    2048li
#facebook_username:  StartBootstrap
linkedin_username:  xiaojuan-li-62521294

disqus:
  shortname: shentanli.disqus.com

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
