title: Shentanli's Blog
author: shentnali
email: shentanli@foxmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Shentanli's career information.
show_excerpts: true # set to true to show excerpts on the homepage
remote_theme: thelehhman/texture
theme: texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Shentanli
  tagline: Information Security Consultant.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: shentanli
    github:  2048li
    linkedIn: in/xiaojuan-li-62521294
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge

plugins:
  - jekyll-seo-tag
#  - jekyll-feed